# cloudbuild.yaml
steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${PROJECT_ID}/h2o-mojo-service', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${PROJECT_ID}/h2o-mojo-service']
    
  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'h2o-mojo-service'
    - '--image'
    - 'gcr.io/${PROJECT_ID}/h2o-mojo-service'
    - '--region'
    - 'us-central1'
    - '--platform'
    - 'managed'
    - '--port'
    - '8080'
    - '--memory'
    - '4Gi'
    - '--cpu'
    - '1'
    - '--min-instances'
    - '0'
    - '--max-instances'
    - '10'
    - '--allow-unauthenticated'

images:
- 'gcr.io/${PROJECT_ID}/h2o-mojo-service'